version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goflash_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=goflash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goflash_net
  redis:
    image: redis:alpine
    container_name: goflash_redis
    ports:
      - "6379:6379"
    networks:
      - goflash_net
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: goflash_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - goflash_net
  
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: goflash_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - goflash_net



volumes:
  postgres_data:

networks:
  goflash_net: